# Use root/example as user/password credentials
version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:80
      - 443:443
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot

  api:
    build: ./api
    environment:
      - MYSQL_ROOT_PASSWORD
      - DATABASE_HOSTNAME
      - ENCRYPTION_KEY
    ports:
      - ${API_PORT}:3001
    networks:
      - default

  db:
    image: percona
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    networks:
      default:
        aliases:
          - ${DATABASE_HOSTNAME}

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"