# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    build: ./frontend
    ports:
      - 80:80

  api:
    build: ./backend
    environment:
      MYSQL_ROOT_PASSWORD
    ports:
      - 3001:3001

  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
