# Use root/example as user/password credentials
version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot

  api:
    build: ./api
    environment:
      - MYSQL_ROOT_PASSWORD
      - ENCRYPTION_KEY
    ports:
      # localhost only for development, this should be proxied through nginx
      - 127.0.0.1:3001:3001

  db:
    image: percona
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      # to share mysqld.cnf overrides
      - ./mysql:/etc/mysql
    ports:
      # localhost to allow SSH->mysql
      - 127.0.0.1:3306:3306

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 72h & wait $${!}; done;'"
