# Use root/example as user/password credentials
version: '3.8'

services:
  # nginx - routes requests to web, api and serves static assets (jason.html for now, this should probably move :)
  frontend:
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        node_env: ${NODE_ENV}
        google_client_id: ${GOOGLE_API_FILBERT_CLIENT_ID}
        encryption_key: ${ENCRYPTION_KEY}
    environment:
      - NODE_ENV
      - MYSQL_ROOT_PASSWORD
      - ENCRYPTION_KEY
    #ports:
      # for local development testing
      #- 127.0.0.1:3000:3000

  tinsey:
    build:
      context: ./tinsey
      dockerfile: ./tinsey/Dockerfile
      args: # build-time environment vars
        node_env: ${NODE_ENV}
        google_client_id: ${GOOGLE_API_FILBERT_CLIENT_ID}
    environment: # runtime environment vars
      - NODE_ENV
      - MYSQL_ROOT_PASSWORD

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - NODE_ENV
      - MYSQL_ROOT_PASSWORD
      - ENCRYPTION_KEY
      - GOOGLE_API_FILBERT_CLIENT_ID
      - LINODE_OBJECT_STORAGE_ACCESS_KEY
      - LINODE_OBJECT_STORAGE_SECRET_ACCESS_KEY
    #ports:
      # localhost only for development, this should be proxied through nginx
      #- 127.0.0.1:3001:3001

  db:
    image: percona
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      # to share mysqld.cnf overrides
      - ./mysql:/etc/mysql
    ports:
      # localhost to allow SSH->mysql
      - 127.0.0.1:3306:3306

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 72h & wait $${!}; done;'"
