# Use root/example as user/password credentials
version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:80

  api:
    build: ./api
    environment:
      - MYSQL_ROOT_PASSWORD
      - DATABASE_HOSTNAME
    ports:
      - ${API_PORT}:3001
    networks:
      - default

  db:
    image: percona
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    networks:
      default:
        aliases:
          - ${DATABASE_HOSTNAME}
